### PR TITLE
Enable windows builds

### PR DESCRIPTION
**Pull request by photex**
Howdy!

I'm strange I guess but I work on Windows and Linux both and figured it'd be nice to be able to use this crate on each platform. The essential takeaway from this PR is just that you can't rely on the `nix` crate when building/working on Windows.

I don't expect this to be merged exactly how it is. Main trip up was with the `error_chain!` usage as there didn't seem to be a better way to have a version that didn't include the Nix error without resorting to copy-pasta.

For gethostname there is a cross-platform crate to do this... maybe it's silly to pull that in rather than replicate what it does. I dunno how you feel about that.

For getpid the rust standard library has a function for this already, but perhaps it isn't working quite the same way.

I haven't yet managed to build and test this crate in it's entirety because I don't have the roscpp_tutorials messages apparently.

### CODE REVIEW

**Comment by adnanademovic** [comment]
Thanks for the effort here.
Just a few things:

- Just leave the library version as is. I'll make a major bump once the time is right, since there were massive API changes in master compared to the 0.7 release.
- Regarding error chain: it would be easier to remove the `nix` error type as a foreign link, and just make explicit errors for all instances where `nix` errors would be called.

I'll take a look at this later. Honestly I never even considered running/building on windows, due to never using ROS on it.

**Comment by 6xzo** [comment]
I too needed this on Windows and my good intentions to share my changes remained just that, for which I apologize. I completely eliminated use of nix and just used hostname on all platforms. This solved the error problem by eliminating the Nix error outright. I approached dealing with the pid type mismatch with a transmute so that their domain is the same size and which I think is OK since the PID is just used as a token. Finally, we also changed codegen to accept CRLF input.

Here is a summary of my changes for you to consider. They are against a commit from a couple months ago. I can't commit to updating them at this time.

```
rosrust/Cargo.toml:
- nix = "0.9.0"
+ hostname = "0.1"

rosrust/src/api/error.rs:
- Nix(::nix::Error);

rosrust/src/api/resolve.rs:
fn system_hostname() -> String {
    use hostname::get_hostname;
    get_hostname().unwrap()
}

rosrust/src/api/slave/handler.rs:
- use nix::unistd::getpid;
let pid = std::process::id();
let pid = unsafe { std::mem::transmute(pid) };
server.register_value("getPid", "PID", move |_args| Ok(Value::Int(pid)));

rosrust/src/lib.rs:
+ extern crate hostname;
- extern crate nix;

rosrust_codegen/src/helpers.rs:
- let re = RegexBuilder::new("^---$").multi_line(true).build()?;
+ let re = RegexBuilder::new("^---\r?$").multi_line(true).build()?;
```

**Comment by neachdainn** [comment]
I don't have much to add as far as Windows goes, but I can comment that the ability to run ROS nodes (or, at the very least, being able to build them) on machines that aren't Ubuntu is one of the major appeals of this crate. Much of my development is done on either Arch Linux or macOS and not having to drop into an Ubuntu VM just to check if something will compile has been fantastic. I'm sure Windows users will feel the same way.

**Comment by photex** [comment]
Sorry for the delay updating the PR @adnanademovic. Nix isn't really needed in it's current state as far as I can tell.

@6xzo I'd be happy to try and include your update to rosrust_codegen but we'd want to somehow support both kinds of line ending. So far I haven't been bitten by `\r\n` but I haven't extensively used the codegen yet.

My work with this so far has been working on a bridge between ros1 and another bus and trying to just transcode messages.

**Comment by photex** [comment]
Trying to bring my branch back up to date. Tests aren't building due to the removed nix dep. I'll get that fixed.

**Comment by romainreignier** [comment]
Thanks to @photex effort, I have managed to create an up-to-date branch with Windows support and made the tests pass: https://github.com/romainreignier/rosrust/commit/2914a30b303ca13eef1cc685069af9d9c2ccd452

Note that I have replaced the `SIGINT` call by `std::process::Child::kill()` call that do a `SIGKILL`. I am not sure if this is an issue.
What do you think @adnanademovic ?

I have built the `subscriber_node` with [cross](https://github.com/rust-embedded/cross) and the `x86_64-pc-windows-gnu` target and run it with success on a Windows PC.
This issue with cross is that it uses a Docker container to cross-compile so I had to create a new image in which I have installed `ros-melodic-std-msgs` in order to have the `std_msgs` installed:
```
FROM rustembedded/cross:x86_64-pc-windows-gnu-0.2.0

# Install ros to have std_msgs
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt install  --no-install-recommends -q -y \
    dirmngr \
    gnupg2 \
    lsb-release
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt update && apt install --no-install-recommends -y -q ros-melodic-std-msgs
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
```
```sh
$ docker build -t cross:x86_64-pc-windows-gnu-0.2.0-with-ros-std-msgs .
```

Used it with `cross` so I set `Cross.toml` to:
```toml
[target.x86_64-pc-windows-gnu]
image = "cross:x86_64-pc-windows-gnu-0.2.0-with-ros-std-msgs"

[build.env]
passthrough = ["ROSRUST_MSG_PATH"]
```

And then, call `cross` with:
```sh
export ROSRUST_MSG_PATH=/opt/ros/melodic/share
cross build --target x86_64-pc-windows-gnu --release --example subscriber_node
```

It would be nice to setup a CI job with that workflow. But I am not used to Travis. Maybe a Github action using [this helper](https://github.com/actions-rs/cargo#cross-compilation) could help.

**Comment by romainreignier** [comment]
A couple of tests are failing in the cross-compile environments but it may not be too surprising.
```
test api::resolve::tests::hostname_prioritizes_argument_when_both_passed ... FAILED
test api::resolve::tests::hostname_prioritizes_hostname_over_ip_argument_when_passed ... FAILED
test api::resolve::tests::hostname_prioritizes_hostname_over_ip_environment_when_passed ... FAILED
test api::resolve::tests::hostname_uses_default_uri_by_default ... FAILED
test api::resolve::tests::hostname_uses_hostname_argument_when_passed ... FAILED
test api::resolve::tests::hostname_uses_hostname_environment_when_passed ... FAILED
test api::resolve::tests::hostname_uses_ip_argument_when_passed ... FAILED
test api::resolve::tests::hostname_uses_ip_environment_when_passed ... FAILED
test api::resolve::tests::mappings_default_to_empty_vector ... FAILED
test api::resolve::tests::mappings_maps_good_and_ignores_everything_else ... FAILED
test api::resolve::tests::master_prioritizes_argument_when_both_passed ... FAILED
test api::resolve::tests::master_uses_argument_when_passed ... FAILED
test api::resolve::tests::master_uses_default_uri_by_default ... FAILED
test api::resolve::tests::master_uses_environment_when_passed ... FAILED
test api::resolve::tests::name_uses_argument_when_provided ... FAILED
test api::resolve::tests::name_uses_passed_value_by_default ... FAILED
test api::resolve::tests::namespace_prioritizes_argument_when_both_passed ... FAILED
test api::resolve::tests::namespace_uses_argument_when_passed ... FAILED
test api::resolve::tests::namespace_uses_empty_string_by_default ... FAILED
test api::resolve::tests::namespace_uses_environment_when_passed ... FAILED
test api::resolve::tests::params_default_to_empty_vector ... FAILED
test api::resolve::tests::params_maps_good_and_ignores_everything_else ... FAILED
```

**Pull request merged**
