### PR TITLE
Improve message parsing performance

### PR DESCRIPTION
**Pull request by chachi**
Collectively these two commits took message parsing from 57% of my image handling node's runtime to < 1%.

There are some `unsafe` blocks in order to handle stream reading without requiring initialization of the memory buffers. This seems unavoidable without alternative APIs.

### CODE REVIEW

**Comment by adnanademovic** [comment]
Just to check: is the speedup happening when compiling both versions with the "--release" flag?

**Comment by chachi** [comment]
Yup, both versions were built with release. I saw between 30% and 60% of the program going to rosrust message handling before the change.

**Comment by adnanademovic** [comment]
LGTM. Thoroughly checked it out, because `unsafe` warrants a lot of precaution.

**Comment by chachi** [comment]
Awesome! And yeah, the more eyeballs and tests on `unsafe`s the better!

**Pull request merged**
