### PR TITLE
implement wait_for_service()

### PR DESCRIPTION
**Pull request by astraw**
Here's an implementation of wait_for_service() that is working for me. I'm happy to address any issues.

### CODE REVIEW

**Comment by adnanademovic** [comment]
Nice idea! Maybe add a timeout option?

Also, the code can be flattened a bit, by using early returns:

``` rust
let name = self.resolver.translate(service)?;
loop {
    let e = match self.master.lookup_service(&name) {
        Ok(_) => return Ok(()),
        Err(e) => e,
    };
    match e.kind() {
        &Api(BadData(ref m)) if m == "no provider" => {
            sleep(Duration::from_millis(100));
        },
        _ => return Err(e.into()),
    }
}
```

**Comment by astraw** [comment]
Good idea about a timeout option -- that's also in the Python API. I implemented it.

I would also like to get rid of some of the right-shift but your flattening doesn't work because `e.kind()` borrows `e` and thus `return Err(e.into())` later in the following block fails borrowck.

**Comment by adnanademovic** [comment]
I'm not at a computer to test things, but in the code I provided then:

``` rust
match e.kind() {
    &Api(BadData(ref m)) if m == "no provider" => {
        sleep(Duration::from_millis(100));
    },
    _ => return Err(e.into()),
}
```

could become:

``` rust
match e.kind() {
    &Api(BadData(ref m)) if m == "no provider" => {
        sleep(Duration::from_millis(100));
    },
    _ => {}
} // stops borrowing
return Err(e.into());
```

Your implementation already does that as far as I see.

**Comment by astraw** [comment]
Ah, yes. Flattened.

**Pull request merged**
